from __future__ import annotations

import ast
import re
import tokenize
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "eocrc_dat"

FORBIDDEN = (
    "reproduction of",
    "based on the paper",
    "re-implementation",
    "following the authors",
    "as described by",
    "generated by",
    "ai-assisted",
    "skeleton",
    "placeholder",
    "todo from paper",
    "comprehensive",
    "state-of-the-art",
    "cutting-edge",
    "seamlessly",
    "leveraging",
    "utilize",
    "delve",
    "holistic",
    "meticulously",
    "it's worth noting",
    "in conclusion",
)

EMOJI = re.compile(
    "[\U0001f000-\U0001faff\U00002600-\U000027bf\U0001f1e6-\U0001f1ff\U00002b00-\U00002bff]"
)


def _python_files() -> list[Path]:
    return [path for path in PACKAGE.rglob("*.py")]


def test_no_comments_in_package() -> None:
    offenders: list[str] = []
    for path in _python_files():
        with path.open("rb") as handle:
            for token in tokenize.tokenize(handle.readline):
                if token.type == tokenize.COMMENT:
                    offenders.append(f"{path.name}:{token.start[0]}")
    assert not offenders, offenders


_DEF_NODES = (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)


def test_no_docstrings_in_package() -> None:
    offenders: list[str] = []
    for path in _python_files():
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if isinstance(node, _DEF_NODES) and ast.get_docstring(node) is not None:
                offenders.append(f"{path.name}:{getattr(node, 'name', 'module')}")
    assert not offenders, offenders


def test_no_forbidden_phrases_or_emoji() -> None:
    targets = list(_python_files())
    for extra in ("README.md", "Makefile"):
        candidate = ROOT / extra
        if candidate.exists():
            targets.append(candidate)
    offenders: list[str] = []
    for path in targets:
        text = path.read_text(encoding="utf-8")
        lowered = text.lower()
        for phrase in FORBIDDEN:
            if phrase in lowered:
                offenders.append(f"{path.name}:{phrase}")
        if EMOJI.search(text):
            offenders.append(f"{path.name}:emoji")
    assert not offenders, offenders
